import React, { useMemo, useState, useEffect } from 'react';
import api from '../api/client';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Terminal, 
  Copy, 
  Download, 
  FileCode, 
  Check, 
  Loader2, 
  UploadCloud, 
  TrendingUp,
  AlertCircle,
  Zap
} from 'lucide-react';
import { useAgent } from '../context/AgentContext';
import { toast } from 'sonner';

// ✅ Premium Syntax Highlighting
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { atomDark, oneLight } from 'react-syntax-highlighter/dist/esm/styles/prism';

const CodeGenerator = () => {
  const { sessionId, includeTestSplit, strategy, getAIStrategy, setStrategy, updateProgress } = useAgent();
  const [loading, setLoading] = useState(!strategy);
  const [copied, setCopied] = useState(false);
  const isLight = document.documentElement.getAttribute('data-theme') === 'light';
  
  // Feedback Loop State
  const [uploadingResults, setUploadingResults] = useState(false);
  const [feedback, setFeedback] = useState(null);

  useEffect(() => {
    if (!strategy) {
      getAIStrategy().finally(() => setLoading(false));
    }
  }, [strategy, getAIStrategy]);

  const pythonCode = useMemo(() => {
    if (!strategy) return "";

    const formatParamsWithComments = (params, filterKey = null) => {
      if (!params || typeof params !== 'object') return ""; 
      return Object.entries(params)
        .filter(([k]) => k !== filterKey)
        .map(([k, v]) => {
          let formattedValue;
          if (typeof v === 'boolean') {
            formattedValue = v ? 'True' : 'False';
          } else if (typeof v === 'string') {
            formattedValue = `"${v}"`;
          } else {
            formattedValue = JSON.stringify(v);
          }
          
          const explanation = strategy.explanations?.[k];
          const comment = explanation ? `  # ${explanation}` : '';
          
          return `        ${k}=${formattedValue},${comment}`;
        }).join('\n');
    };

    return `
# -------------------------------------------------------------------------
# 🚀 PRODUCTION-GRADE YOLO TRAINING PIPELINE
# Generated by AutoYOLO Expert Agent (v2.1)
# 
# DATASET AUDIT SUMMARY:
# ${(strategy?.reasoning || "Neural generation in progress...").split('\n').join('\n# ')}
# 
# HOW TO RUN:
# 1. Ensure you have ultralytics and torch installed: pip install ultralytics torch
# 2. Place your 'data.yaml' in the same directory as this script.
# 3. Execute: python production_train.py
# -------------------------------------------------------------------------

from ultralytics import YOLO
import torch
import matplotlib.pyplot as plt
import pandas as pd
import os

def plot_training_results(results_path="runs/detect/train/results.csv"):
    """
    📊 RECURSIVE METRICS ANALYSIS
    Generates a professional visualization of the training convergence.
    """
    if not os.path.exists(results_path):
        print(f"⚠️ Warning: {results_path} not found. Ensure training completed successfully.")
        return
        
    df = pd.read_csv(results_path)
    df.columns = [c.strip() for c in df.columns]
    
    fig, ax = plt.subplots(1, 2, figsize=(15, 6))
    plt.style.use('dark_background')
    
    # --- Precision / Recall Metrics ---
    ax[0].plot(df['metrics/mAP50-95(B)'], color='#00ff88', lw=2, label='mAP@50-95')
    ax[0].set_title('Model Accuracy (mAP)', color='#00ff88', fontsize=12, pad=15)
    ax[0].grid(alpha=0.1)
    ax[0].legend()
    
    # --- Convergence Analysis ---
    ax[1].plot(df['train/box_loss'], color='#ff3366', lw=2, label='Box Loss')
    ax[1].plot(df['train/cls_loss'], color='#3366ff', lw=2, label='Class Loss')
    ax[1].set_title('Training Loss Breakdown', color='#ff3366', fontsize=12, pad=15)
    ax[1].grid(alpha=0.1)
    ax[1].legend()
    
    plt.tight_layout()
    plt.savefig('training_analytics.png', dpi=300)
    print("✅ Analytics exported to 'training_analytics.png'")

def run_expert_training():
    """
    🛠️ EXECUTION ENGINE
    Initializes model and begins optimized training suite.
    """
    print("📡 Initializing Neural Architecture...")
    
    # 1. Automatic Hardware Detection
    device = "0" if torch.cuda.is_available() else "cpu"
    print(f"✅ Compute Target: {device}")

    # 2. Model Initialization (AI Optimized Selection)
    model = YOLO("${strategy.recommended_model}")

    # 3. Intelligence-Driven Training Suite
    print("🚀 Launching Optimized Training Pipeline...")
    model.train(
        data="data.yaml",
        # --- STRATEGY PARAMETERS ---
${formatParamsWithComments(strategy.train_params, 'device')}
        # --- AUGMENTATION SUITE ---
${formatParamsWithComments(strategy.aug_params)}
        # --- SYSTEM CONFIG ---
        device=device,
        exist_ok=True,
    )

    # 4. Neural Audit & Validation
    print("📊 Performing Post-Training Audit...")
    model.val()
    
    ${includeTestSplit ? `
    # 5. Production evaluation on [TEST] split
    print("🏆 Running final evaluation on test split...")
    model.val(split='test')
    ` : ''}

    # 6. Recursive Feedback Plotting
    plot_training_results()

    # 7. Export for Edge Deployment
    print("📦 Exporting weights to ONNX for production deployment...")
    model.export(format="onnx")
    
    print("\\n🚀 SUCCESS: Intelligent Training Pipeline Complete.")

if __name__ == "__main__":
    run_expert_training()
    `.trim();
  }, [strategy, includeTestSplit]);

  const handleCopy = () => {
    navigator.clipboard.writeText(pythonCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([pythonCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'production_train.py';
    link.click();
  };

  const handleResultsUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setUploadingResults(true);
    const formData = new FormData();
    formData.append('logs', file);

    try {
      const res = await api.post(`/feedback/${sessionId}`, formData);
      if (res.data.status === "success") {
        setFeedback({ 
          ...res.data.feedback, 
          updated_strategy: res.data.updated_strategy 
        });
      }
    } catch (err) {
      console.error(err);
    } finally {
      setUploadingResults(false);
    }
  };

  if (loading) return (
    <div className="p-20 flex flex-col items-center justify-center gap-4">
      <Loader2 className="text-ui-accent animate-spin" size={40} />
      <p className="text-ui-accent font-mono text-xs tracking-[0.3em] animate-pulse">GENERATING EXPERT SCRIPT...</p>
    </div>
  );

  return (
    <div className="w-full max-w-6xl mx-auto px-4 pb-20">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* CODE PANEL */}
        <div className="lg:col-span-2 space-y-4">
          <div className="bg-ui-card border border-ui-border rounded-[2.5rem] overflow-hidden shadow-2xl">
            <div className="bg-ui-surface px-8 py-4 flex justify-between items-center border-b border-ui-border">
              <span className="text-[10px] font-mono text-ui-muted uppercase tracking-widest flex items-center gap-2">
                <FileCode size={14} className="text-ui-accent" /> production_train.py
              </span>
              <div className="flex gap-4">
                <motion.button 
                  whileHover={{ scale: 1.05, color: "var(--ui-accent)" }}
                  whileTap={{ scale: 0.95 }}
                  onClick={handleDownload}
                  className="text-ui-muted hover:text-ui-text transition-all flex items-center gap-2 text-[10px] font-bold"
                >
                  <Download size={14} /> DOWNLOAD
                </motion.button>
                <motion.button 
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={handleCopy} 
                  className={`text-[10px] font-bold transition-all flex items-center gap-2 ${copied ? 'text-ui-accent' : 'text-ui-muted hover:text-ui-text'}`}
                >
                  {copied ? <><Check size={14} /> COPIED!</> : <><Copy size={14} /> COPY</>}
                </motion.button>
              </div>
            </div>
            
            {/* ✅ REFINED CODE DISPLAY: Removed white line backgrounds and borders */}
            <div className="px-8 py-6 max-h-[600px] overflow-y-auto scrollbar-thin bg-ui-surface/50 selection:bg-ui-accent/20">
              <SyntaxHighlighter 
                language="python" 
                style={isLight ? oneLight : atomDark}
                wrapLongLines={true}
                customStyle={{ 
                  background: 'transparent', 
                  padding: 0, 
                  margin: 0, 
                  fontSize: '11px',
                  lineHeight: '1.6',
                  border: 'none',
                  boxShadow: 'none',
                  backgroundColor: 'transparent'
                }}
                codeTagProps={{
                  style: {
                    background: 'transparent',
                    border: 'none',
                    backgroundColor: 'transparent'
                  }
                }}
              >
                {pythonCode}
              </SyntaxHighlighter>
            </div>
          </div>
        </div>

        {/* FEEDBACK & RECURSION PANEL */}
        <div className="space-y-6">
          <div className="bg-ui-card border border-ui-border rounded-[2.5rem] p-8 shadow-2xl relative overflow-hidden group">
            <div className="absolute top-0 right-0 w-24 h-24 bg-ui-accent/5 blur-[40px] pointer-events-none" />
            
            <h3 className="text-ui-text font-black text-xl italic mb-4 flex items-center gap-3">
              <TrendingUp className="text-ui-accent" size={20} />
              RECURSIVE FEEDBACK
            </h3>
            <p className="text-ui-muted text-sm mb-8 leading-relaxed font-bold uppercase tracking-tight opacity-70">
              Ran the script? Upload your <code className="text-ui-accent bg-ui-accent/5 px-1 rounded">results.csv</code> here for a deep-learning audit.
            </p>

            <label className="cursor-pointer block">
              <motion.div 
                whileHover={{ scale: 1.02, backgroundColor: "var(--ui-card-hover)", borderColor: "var(--ui-accent)" }}
                whileTap={{ scale: 0.98 }}
                className="w-full py-10 border-2 border-dashed border-ui-border rounded-3xl flex flex-col items-center justify-center gap-3 transition-all text-ui-muted hover:text-ui-accent"
              >
                {uploadingResults ? (
                  <Loader2 className="animate-spin" size={30} />
                ) : (
                  <>
                    <UploadCloud size={30} />
                    <span className="text-[10px] font-black tracking-widest uppercase">UPLOAD RESULTS</span>
                  </>
                )}
                <input type="file" className="hidden" accept=".csv" onChange={handleResultsUpload} disabled={uploadingResults} />
              </motion.div>
            </label>

            <AnimatePresence>
              {feedback && (
                <motion.div 
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="mt-8 p-6 bg-ui-surface border border-ui-accent/20 rounded-2xl relative"
                >
                  <div className={`text-[10px] font-black tracking-widest uppercase mb-2 ${feedback.verdict === 'Production Ready' ? 'text-ui-accent' : 'text-yellow-500'}`}>
                    VERDICT: {feedback.verdict}
                  </div>
                  <p className="text-ui-muted text-xs italic leading-relaxed mb-4 font-medium uppercase tracking-tight">
                    "{feedback.feedback}"
                  </p>
                  
                  {feedback.suggested_changes && Object.keys(feedback.suggested_changes).length > 0 && (
                    <div className="pt-4 border-t border-ui-border">
                      <motion.button 
                        whileHover={{ scale: 1.05, backgroundColor: "var(--ui-accent)", color: "#000000" }}
                        whileTap={{ scale: 0.95 }}
                        onClick={() => {
                          if (feedback.updated_strategy) {
                            setStrategy(feedback.updated_strategy);
                            updateProgress(3); // Go back to Hyperparameters tab
                            toast.success("AI feedback integrated. Parameters updated.");
                          }
                        }}
                        className="w-full flex items-center justify-center gap-2 bg-ui-accent/10 border border-ui-accent/20 text-ui-accent py-2 rounded-xl text-[10px] font-black tracking-widest transition-all"
                      >
                        <Zap size={14} /> APPLY REVISIONS & GO TO PARAMETERS
                      </motion.button>
                    </div>
                  )}
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <div className="p-6 bg-ui-accent/5 border border-ui-accent/10 rounded-3xl flex gap-4 items-start">
            <AlertCircle className="text-ui-accent shrink-0" size={20} />
            <p className="text-[10px] text-ui-muted leading-relaxed italic font-bold uppercase tracking-tight">
              AI Expert Note: Training on small datasets? Monitor the <span className="text-ui-text">box_loss</span> slope. If it stagnates before 50% of epochs, consider increasing <span className="text-ui-text">patience</span>.
            </p>
          </div>
        </div>

      </div>
    </div>
  );
};

export default CodeGenerator;